settings:
  # Задержка перед повторной выдачи набора.
  kits-delay: 5

lang:
  prefix: "&aНаборы"

  no-permission: "&cУ вас нет прав!"
  unknown-command: "&cНеизвестная команда!"
  reloaded: "&aКонфигурация перезагружена."
  cooldown: "&aПодождите перед повторным использованием."

  kit-error: "&cОшибка! Используйте: /kit (название)"
  kit-not-found: "&cНабор не найден!"
  kit-received: "&aНабор получен."
  kit-no-access: "&cУ вас нет прав на получение данного набора!"

  edit-error: "&cУкажите кит! Используйте: /kitedit (название)"
  edit-no-access: "&cУ вас нет прав на редактирование данного набора!"
  edit-open: "&aВы открыли редактирование набора. Чтобы сохранить, просто закройте это меню."
  edit-success: "&aНабор был сохранён."
  edit-title: "Редактор Набора"

  preview-error: "&cУкажите кит! Используйте: /kitpreview (название)"
  preview-no-access: "&cУ вас нет прав на редактирование данного набора!"
  preview-open: "&fВы просматриваете набор: &a{kit}"
  preview-title: "Просмотр Набора"

  kits-list: "&fСписок доступных наборов: &a{kits}"
  kits-no-available: "&cДоступные наборы не найдены."
  kits-create-error: "&cОшибка! Используйте: /kits create (название)"
  kit-created: "&aНабор успешно создан!"
  kits-delete-error: "&cОшибка! Используйте: /kits delete (название)"
  kit-deleted: "&aНабор успешно удалён!"
  help-list:
    - "&7--------- {prefix} &7---------"
    - "&a/kit (название) &7- &fПолучить набор."
    - "&a/kits &7- &fСписок доступных наборов."
    - "&a/kits create (название) &7- &fСоздать набор."
    - "&a/kits delete (название) &7- &fУдалить набор."
    - "&a/kits reload &7- &fПерезагрузить конфиг."